image: debian/stable
packages:
  - clang
  - gcc
  - tcc
  - libsdl2-dev
  - libsdl2-image-dev
  - libsdl2-mixer-dev
sources:
  - https://git.sr.ht/~ashn/autil
tasks:
  - test-clang-debug: |
      cd autil
      make clean check CC=clang CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - test-clang-release: |
      cd autil
      make clean check CC=clang CFLAGS='$(GNU_REL)'
  - test-gcc-debug: |
      cd autil
      make clean check CC=gcc CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - test-gcc-release: |
      cd autil
      make clean check CC=gcc CFLAGS='$(GNU_REL)'
  - test-tcc: |
      cd autil
      make clean check CC=tcc
  - examples-clang: |
      cd autil
      make clean examples CC=clang CFLAGS='$(GNU_REL)'
  - examples-gcc: |
      cd autil
      make clean examples CC=gcc CFLAGS='$(GNU_REL)'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
